#!/usr/bin/env ruby
require_relative 'lib/environment'
require_relative 'lib/apt_complex'
require_relative 'lib/complex_parse_arguments'

command = ARGV[0]
type = ARGV[1]
options = ComplexParser.parse

if command == 'create'
  error_message = ComplexParser.validate(options)

  if error_message.nil?
    complex = AptComplex.new(name: options[:name], zip: options[:zip], parking: options[:parking], website: options[:website], phone: options[:phone])
    complex.create (options[:environment])
    puts "Complex #{options[:name]} was created."
  else
    puts error_message
  end
elsif command == 'view'
  puts AptComplex.view(options[:environment])
end
